STAT 2255: Homework 03
======================



## Problem 1



### (a) 15 pts



Create a numpy array that consists of the first $n$ positive integers, i.e., 1,
2, 3, &#x2026;, n, and calculate
$$S=\sqrt{\sum_{i=1}^{n}\frac{6}{i^2}}$$
for $n=10^7$.
Do the same by creating a List without using numpy, and compare the times of
using the two approaches.



In [1]:
import numpy as np
import time, math
n = 10**7

start = time.time()
arr = np.arange(1, n+1)
print(np.sqrt(np.sum(6 / arr**2)))
print("Time used: ", time.time() - start)

start = time.time()
L = list(range(1, n+1))
L1 = [6 / (x ** 2) for x in L]
math.sqrt(sum(L1))
print("Time used: ", time.time() - start)

3.141592558096831
Time used:  0.06729912757873535
Time used:  0.44691014289855957


### (b) 15 pts



For the array `arr3` created using the following code,



In [2]:
np.random.seed(2255)
arr3 = 4 * np.random.standard_normal(10)

return the fractional parts as `f` and integral part as `h`. Convert `f` and `h`
to arrays of floats32 and int32, respectively. Check the memory usage of `f` and
`h`, and the arrays with the converted types. You can use `.nbytes` to check the
memory useage, e.g., `f.nbytes`.



In [3]:
f, h = np.modf(arr3)
print(f)
f_32 = f.astype(np.float32)
h_32 = h.astype(np.int32)
print(f.nbytes, h.nbytes, f_32.nbytes, h_32.nbytes)

[ 0.44620036  0.72663964  0.94378582  0.85475987 -0.31598788  0.52501821
  0.22479145  0.81553638 -0.8113339   0.2323483 ]
80 80 40 40


## Problem 2



Use the same **data.csv** file in the previous homework for this problem.



### (a) 5 pts



The `genfromtxt` function from numpy can read data from the disk. Use it to read
the data from **data.csv** to a variable `dat` and show the data type of its
elements.



In [4]:
dat = np.genfromtxt('data.csv')
dat.dtype

dtype('float64')

### (b) 5 pts



Create an numpy array `dat1` using the first 10 and last 53 elements of `dat`.

In [5]:
idx = np.arange(0, dat.size)
dat1 = dat[(idx < 10) | (idx >= 47)]
dat1

array([1.99481643, 4.03537549, 4.40020905, 3.39779016, 5.54115129,
       4.16097856, 4.1470556 , 3.13504154, 2.18810337, 6.26358593,
       5.13101805, 4.25742578, 2.27809081, 3.67814695, 2.26326134,
       4.55232344, 4.38656059, 3.42848759, 2.8808863 , 2.89811444,
       2.63891705, 2.92433758, 4.29882373, 3.52627961, 2.45511137,
       2.98525864, 3.1445444 , 5.11857156, 3.85823832, 2.74079499,
       2.54121291, 3.39138421, 2.89681925, 4.00545117, 1.49084575,
       3.22887692, 2.78585735, 2.18174929, 4.06393512, 4.24789188,
       3.18271838, 3.89326462, 2.98155131, 4.73982186, 3.47011743,
       3.70594027, 3.79289101, 4.40968881, 3.81994709, 3.88410645,
       4.8394019 , 1.26591707, 4.59906115, 3.95111215, 0.54318772,
       4.4095936 , 5.16892213, 2.76687134, 3.01359531, 3.73942551,
       3.41735413, 5.1344182 , 4.36772034])

In [6]:
n = len(dat)
np.concatenate((dat[0:10], dat[n-53:n]))

array([1.99481643, 4.03537549, 4.40020905, 3.39779016, 5.54115129,
       4.16097856, 4.1470556 , 3.13504154, 2.18810337, 6.26358593,
       5.13101805, 4.25742578, 2.27809081, 3.67814695, 2.26326134,
       4.55232344, 4.38656059, 3.42848759, 2.8808863 , 2.89811444,
       2.63891705, 2.92433758, 4.29882373, 3.52627961, 2.45511137,
       2.98525864, 3.1445444 , 5.11857156, 3.85823832, 2.74079499,
       2.54121291, 3.39138421, 2.89681925, 4.00545117, 1.49084575,
       3.22887692, 2.78585735, 2.18174929, 4.06393512, 4.24789188,
       3.18271838, 3.89326462, 2.98155131, 4.73982186, 3.47011743,
       3.70594027, 3.79289101, 4.40968881, 3.81994709, 3.88410645,
       4.8394019 , 1.26591707, 4.59906115, 3.95111215, 0.54318772,
       4.4095936 , 5.16892213, 2.76687134, 3.01359531, 3.73942551,
       3.41735413, 5.1344182 , 4.36772034])

### (c) 5 pts



Reshape `dat1` to a matrix of 7 rows and 9 columns. Calculate the column sum
and the row sum, and the sum of all elements.



In [7]:
datm = dat1.reshape((7, 9))
print(datm.sum(axis=0))
print(datm.sum(axis=1))
print(datm.sum(axis=(0, 1)))

[23.29284556 26.3069802  27.67989292 21.97614177 26.98992633 25.31943079
 22.82476409 26.47100773 23.7789622 ]
[33.00052149 36.23890048 27.75227312 29.27219508 31.54690725 34.26806589
 32.56108828]
224.63995159347857


### (d) 5 pts



Replace the elements in `datm` that are larger than 3 by 3 and the elements
smaller than 1 by 0.



In [8]:
datm[datm > 3] = 3
datm[datm < 1] = 0
datm

array([[1.99481643, 3.        , 3.        , 3.        , 3.        ,
        3.        , 3.        , 3.        , 2.18810337],
       [3.        , 3.        , 3.        , 2.27809081, 3.        ,
        2.26326134, 3.        , 3.        , 3.        ],
       [2.8808863 , 2.89811444, 2.63891705, 2.92433758, 3.        ,
        3.        , 2.45511137, 2.98525864, 3.        ],
       [3.        , 3.        , 2.74079499, 2.54121291, 3.        ,
        2.89681925, 3.        , 1.49084575, 3.        ],
       [2.78585735, 2.18174929, 3.        , 3.        , 3.        ,
        3.        , 2.98155131, 3.        , 3.        ],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        , 1.26591707, 3.        , 3.        ],
       [0.        , 3.        , 3.        , 2.76687134, 3.        ,
        3.        , 3.        , 3.        , 3.        ]])

### (e) 5 pts



What is the number of elements in `datm` from the previous problem that have
zero reminder.



In [9]:
(np.modf(datm)[0] == 0).sum()

44

### (f) 10 pts



Let $X$ be the matrix consisting of the first 7 columns of `datm` and $Y$ be the
matrix consisting of the last 2 columns of `datm`. Calculate
$X^{-1}Y$.



In [10]:
X = datm[:,0:7]
Y = datm[:,7:]
np.linalg.inv(X) @ Y

array([[-0.48020932, -0.21989334],
       [-0.4579646 , -1.19138552],
       [-1.44930918, -1.2175685 ],
       [ 4.10901628, -1.60104635],
       [ 4.07741747,  5.3144577 ],
       [-4.68149062,  0.16678951],
       [-0.27835954, -0.59566344]])

### (g) 10 pts



For the `X` and `error` created with the following code,



In [11]:
np.random.seed(2255)
n, p = 1000, 7
X = np.random.standard_normal((n, p))
error = np.random.standard_normal(n)

create $Y$ from equation
$$Y = X \beta + error$$
where $\beta=(1, 1, 2, 3, 2, 1, 1)'$. Calculate the least squares estimator of
$\beta$ defined as
$$b=(X'X)^{-1}X'Y$$



In [12]:
beta = np.array([1, 1, 2, 3, 2, 1, 1])
Y = X @ beta + error
b = np.linalg.inv(X.T @ X) @ (X.T @ Y)
b

array([1.0363174 , 0.96346003, 2.00324042, 3.04953088, 1.99688085,
       0.9947966 , 0.99267029])

### (h) 25 pts



Repeat the least squares simulation in the previous step for $R=1000$ times. At
each repetition, generate a new `X`, `error`, and `Y`, but generate `X` with
`np.random.multivariate_normal(mu, Sigma, n)`, where `mu` and `Sigma` are
created with the following code. Calculate the least
squares estimates for all repetitions and save them as rows of an array `result` with $R$
rows and 7 columns.

1.  Calculate the variances for the 7 columns of `result`. This is using a
    simulation to estimate the variance of the least squares estimator. Remember
    to set the random seed with `np.random.seed(2255)` in the beginning of the
    code.
2.  Obtain the diagonal elements the inverse of `Sigma` divided by $n$, i.e.,
    $$\frac{\text{Sigma}^{-1}}{n}.$$
    Compare the results with the variances from the previous step. You may try increase
    or decrease $R$ to see how the comparison changes.



In [13]:
n, p = 100, 7
mu = np.zeros(p)
rho = 0.5
Sigma = np.zeros((p, p))
for i in range(p):
    for j in range(p):
        Sigma[i, j] = (i+1) * (j+1) * rho ** abs(i - j)

In [14]:
np.random.seed(2255)
beta = np.array([1, 1, 2, 3, 2, 1, 1])
R = 1000
result = np.empty((R, p))

for r in range(0, R):
    error = np.random.standard_normal(n)
    X = np.random.multivariate_normal(mu, Sigma, n)
    Y = X @ beta + error
    b = np.linalg.inv(X.T @ X) @ (X.T @ Y)
    result[r] = b

print(result.var(axis=0))

np.diag(np.linalg.inv(Sigma)) / n

[0.0150301  0.00422679 0.00211938 0.00111068 0.00074947 0.00052019
 0.00028323]


array([0.01333333, 0.00416667, 0.00185185, 0.00104167, 0.00066667,
       0.00046296, 0.00027211])